##开发环境
server:
  port: 8091
#spring:
#  datasource:
#    name:
#    #url: jdbc:mysql://192.168.0.242:3306/bjcard_makeuse?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
#    url: jdbc:mysql://192.168.1.32:3306/bjcard?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
##   url: jdbc:mysql://192.168.1.190:3306/bjcard?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
#    #url: jdbc:mysql://127.0.0.1:3306/bjbank_makeuse?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
#    username: root
#    #password: Tecsun#123
#    password: root
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
 
 
 #人社测试环境
#server:
#  port: 8092
#spring:
#  datasource:
#    name: 
#    url: jdbc:mysql://192.125.53.21:3306/bjcard_makeuse?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
##   url: jdbc:mysql://192.168.1.32:3306/bjcard?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
##    url: jdbc:mysql://192.168.1.190:3306/bjcard?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 123456
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
  